name: Nissan Leaf Widget Updater
on:
  schedule:
    - cron: "21 13 * * *" # 6:21 am PT
    - cron: "18 21 * * *" # 2:18 pm PT
    - cron: "27 3 * * *" # 8:27 pm PT
  workflow_dispatch:
jobs:
  scrape:
    name: Scrape
    uses: kevincon/nissan-connect-scraper/.github/workflows/scraper.yml@networking
    with:
      convert-times-to-timezone: "US/Pacific"
      ref: networking
    secrets:
      user-id: ${{ secrets.NISSAN_CONNECT_USER_ID }}
      password: ${{ secrets.NISSAN_CONNECT_PASSWORD }}
      tailscale-auth-key: ${{ secrets.TAILSCALE_AUTH_KEY }}
      tailscale-oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
      tailscale-oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
      tailscale-tags: ${{ secrets.TAILSCALE_TAGS }}
      tailscale-exit-node-name: ${{ secrets.TAILSCALE_EXIT_NODE_NAME }}
  update:
    name: Update
    needs: scrape
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: ${{ secrets.SMTP_SERVER_ADDRESS }}
          server_port: ${{ secrets.SMTP_SERVER_PORT }}
          secure: true
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "#nissan-connect"
          to: trigger@applet.ifttt.com
          from: "\"Nissan Leaf Widget Updater\" <${{ secrets.SMTP_FROM_EMAIL_ADDRESS }}>"
          body: |
            🔌 ${{ needs.scrape.outputs.charger-state }}
            🔋 ${{ needs.scrape.outputs.battery-state-of-charge }}%
            🛞 ${{ needs.scrape.outputs.range-minimum }} - ${{ needs.scrape.outputs.range-maximum }} miles
            🌡️ ${{ needs.scrape.outputs.interior-temperature-range }}
            ⚡️⏳ ${{ needs.scrape.outputs.level-two-charger-eta }}
            👀 ${{ needs.scrape.outputs.last-refresh-date }}
